@startuml C4_Test
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(humanAlias, "User", "The Cat Owner")
Container(cattoiioAlias, "Cattoi.io", "Device", "The system takes cues from the user and controls the ARGB service",$link="https://raw.githubusercontent.com/powellkjr/cattoi.io/main/L2_cattoi.io.puml")
Person(catAlias, "User", "The Cat")

Rel(humanAlias, cattoiioAlias, "Wifi", "web service")
Rel(cattoiioAlias, catAlias, "Visual", "argb service")
Rel(humanAlias, catAlias, "Visual", "watching")
@enduml
