@startuml L2_cattoiio
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LANDSCAPE()

Person(humanAlias, "User", "The Cat Owner")

System_Boundary(lv2_cattoiioAlias, "Cattoi.io Container", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container(cattoiio_webservice, "Cattoi.io Web Service", "Python", $descr="Allows users to confiugre and interact with profiles", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
    Container(cattoiio_hardware, "Cattoi.io Hardware", "Linux, ARGB", $descr="Allows user to reset the Wifi Configuration and the cat to chase the lights", $link="https://raw.githubusercontent.com/powellkjr/cattoi.io/main/circutDesign_bb.png")
}

Person(catAlias, "User", "The Cat")

Rel(humanAlias,cattoiio_webservice, "Uses" , "HTTP")
Rel(humanAlias,cattoiio_hardware, "Uses" , "Touch")

Rel_L(catAlias,cattoiio_hardware, "Uses" , "Touch")
Rel(catAlias,cattoiio_hardware, "Uses" , "Vision")
Rel_L(cattoiio_hardware,cattoiio_webservice,"Reset","GPIO")
@enduml
